spring:
  profiles:
    active:
      - local
    group:
      local:
        - mysql
        - mybatis

---

spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 1234

---

spring:
  config:
    activate:
      on-profile: mybatis
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml